name: "Build Workflow"

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 21.x]
    steps:
      - uses: actions/checkout@v2
        name: "checking out branch"

      - uses: actions/setup-node@v2
        name: using node.js version ${{matrix.node-version}}
        with:
          node-version: ${{matrix.node-version}}

      - run: npm ci

      - run: npm run build
